// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalEquador.Data;

#nullable disable

namespace PortalEquador.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250223204222_NewUser_1")]
    partial class NewUser_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6d9ed3ff-bebb-42bc-ad07-0255bb0f7edb",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = "7d9ed3ff-bebb-42bc-ad07-0255bb0f7edb",
                            Name = "Guest",
                            NormalizedName = "GUEST"
                        },
                        new
                        {
                            Id = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160",
                            Name = "Supervisor",
                            NormalizedName = "SUPERVISOR"
                        },
                        new
                        {
                            Id = "e9f639de-624f-4a4e-b8bf-2381725462f1",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "e9f639de-624f-4a4e-b8bf-2381725462f2",
                            Name = "DataManager",
                            NormalizedName = "DATAMANAGER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949",
                            RoleId = "e9f639de-624f-4a4e-b8bf-2381725462f1"
                        },
                        new
                        {
                            UserId = "418aa945-3d84-4421-8342-7269ec64d949",
                            RoleId = "e9f639de-624f-4a4e-b8bf-2381725462f1"
                        },
                        new
                        {
                            UserId = "428aa945-3d84-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "438aa945-3d84-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "448aa945-3d84-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "1a2b3c4d-0001-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "2a2b3c4d-0002-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "3a2b3c4d-0003-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "4a2b3c4d-0004-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "5a2b3c4d-0005-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "6a2b3c4d-0006-4421-8342-7269ec64d949",
                            RoleId = "e9f639de-624f-4a4e-b8bf-2381725462f2"
                        },
                        new
                        {
                            UserId = "7a2b3c4d-0007-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "8a2b3c4d-0008-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "9a2b3c4d-0009-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "1b2b3c4d-0010-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "2b2b3c4d-0011-4421-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "1a2b3c4d-0002-4821-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        },
                        new
                        {
                            UserId = "1a2b3c4d-0003-4821-8342-7269ec64d949",
                            RoleId = "cc4fcb01-de88-4c20-b4ac-8df5c2a65160"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PortalEquador.Data.Curriculum.Entities.CurriculumEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EditorId");

                    b.ToTable("CurriculumEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.DisciplinaryNotification.Entity.DisciplinaryNotificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccidentLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Local")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonalInformationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccidentLevelId");

                    b.HasIndex("EditorId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("PersonalInformationId");

                    b.ToTable("DisciplinaryNotificationEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Document.Entity.DocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("PersonalInformationId")
                        .HasColumnType("int");

                    b.Property<int?>("SubTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("EditorId");

                    b.HasIndex("PersonalInformationId");

                    b.HasIndex("SubTypeId");

                    b.ToTable("DocumentEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.DriversLicence.Entity.DriversLicenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LicenceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PersonalInformationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProvisionalExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProvisionalRenewalNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditorId");

                    b.HasIndex("LicenceTypeId");

                    b.HasIndex("PersonalInformationId");

                    b.ToTable("DriversLicenceEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Education.School.Entity.SchoolEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegreeId")
                        .HasColumnType("int");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<int?>("MajorId")
                        .HasColumnType("int");

                    b.Property<int>("PersonalInformationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DegreeId");

                    b.HasIndex("EditorId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("MajorId");

                    b.HasIndex("PersonalInformationId");

                    b.ToTable("SchoolEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Education.University.Entity.UniversityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegreeId")
                        .HasColumnType("int");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<int>("PersonalInformationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DegreeId");

                    b.HasIndex("EditorId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("MajorId");

                    b.HasIndex("PersonalInformationId");

                    b.ToTable("UniversityEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Generic.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "408aa945-3d84-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e64480a-1433-43ef-9bb5-b9dd4a128c69",
                            Email = "adminEquador@teste.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDDabzdwwYKxtgt6+LesUwp8nav7/zzjrMfY2AY6+iCj4Do60b8bUm2IPoM7S3K8Nw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4a986688-c40d-4e50-9493-663c6fd9cec7",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "418aa945-3d84-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "060d1c3b-924a-4deb-9b7b-37d319cdfeff",
                            Email = "aguiar@teste.com",
                            EmailConfirmed = true,
                            FirstName = "António",
                            LastName = "Aguiar",
                            LockoutEnabled = false,
                            NormalizedEmail = "AGUIAR@EQUADOR.COM",
                            NormalizedUserName = "AGUIAR@EQUADOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIlOwhy9+zP7ftx8R5dCk17o9FMIwvY0Ut8jZsZUZ1fawVbYdzemJzoDl4M6LX6ZiQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e9e18ae3-9c8e-4492-bfe9-b6051afbc4b9",
                            TwoFactorEnabled = false,
                            UserName = "aguiar@equador.com"
                        },
                        new
                        {
                            Id = "428aa945-3d84-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5fab76c8-f0c8-4768-b9df-a211fc1bb51b",
                            Email = "dovictor@equador.com",
                            EmailConfirmed = true,
                            FirstName = "Domingos",
                            LastName = "Victor",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOVICTOR@EQUADOR.COM",
                            NormalizedUserName = "DOVICTOR@EQUADOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAu1auTT6Yp9WlnGo5ZR8O0T6zkG/ow+GlImgGMHqGoFhX5kr76bd+Cm6FUHJtMDfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c49f5803-7d25-4c9d-a0fe-3be2b522d3bc",
                            TwoFactorEnabled = false,
                            UserName = "dovictor@equador.com"
                        },
                        new
                        {
                            Id = "438aa945-3d84-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f4e353ad-166f-43ec-a8c5-3a6b0bb676ea",
                            Email = "manioca@equador.com",
                            EmailConfirmed = true,
                            FirstName = "Mateus",
                            LastName = "Nioca",
                            LockoutEnabled = false,
                            NormalizedEmail = "MANIOCA@EQUADOR.COM",
                            NormalizedUserName = "MANIOCA@EQUADOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKqyCWV41YSdK1k/LUuL5KtDN8o7NoTCPq0QbbhfadFjOu+kdD02m30EdSGN2rd3Kw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6ab9fc2b-8717-442b-a659-23ba6676add1",
                            TwoFactorEnabled = false,
                            UserName = "manioca@equador.com"
                        },
                        new
                        {
                            Id = "448aa945-3d84-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "474bbdc3-84d5-4421-9f6e-47a4346c867c",
                            Email = "lumira@equador.com",
                            EmailConfirmed = true,
                            FirstName = "Luís",
                            LastName = "Mira",
                            LockoutEnabled = false,
                            NormalizedEmail = "LUMIRA@EQUADOR.COM",
                            NormalizedUserName = "LUMIRA@EQUADOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJE2ve3a9H1uHX8FrkU5nei26DDJMJB/HJzUfOIPF6PIE/GqPR6AtTA3IIJSdY/caA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0207df34-8a9f-4a48-a5bf-7ca451829214",
                            TwoFactorEnabled = false,
                            UserName = "lumira@equador.com"
                        },
                        new
                        {
                            Id = "1a2b3c4d-0001-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "71bbfde6-72ed-49fa-aa72-8f3f9258ff24",
                            Email = "supervisor.cvx@equador.co.ao",
                            EmailConfirmed = true,
                            FirstName = "Lazáro",
                            LastName = "Mazuela",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERVISOR.CVX@EQUADOR.CO.AO",
                            NormalizedUserName = "SUPERVISOR.CVX@EQUADOR.CO.AO",
                            PasswordHash = "AQAAAAIAAYagAAAAEISdqt+cfB/CCRNhbd7c+7cqt1va5RwD+AopbsRhfg2W4GJ74pZwxX/5WH4WQ6etAA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c705dd6e-8ae9-469c-a23f-c28e97535281",
                            TwoFactorEnabled = false,
                            UserName = "supervisor.cvx@equador.co.ao"
                        },
                        new
                        {
                            Id = "2a2b3c4d-0002-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fd246882-be8a-4252-89d0-17bf52ca42e4",
                            Email = "benedito.equador@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Benedito",
                            LastName = "Joaquim",
                            LockoutEnabled = false,
                            NormalizedEmail = "BENEDITO.EQUADOR@GMAIL.COM",
                            NormalizedUserName = "BENEDITO.EQUADOR@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ2AtkSjJNnD2E/uuJITwpFuY4/OMwCd9E2wKtk0V26I21FZAOaEqcH8rMECY6cdfg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e668588a-e95b-4621-a9eb-f385bad3fa35",
                            TwoFactorEnabled = false,
                            UserName = "benedito.equador@gmail.com"
                        },
                        new
                        {
                            Id = "3a2b3c4d-0003-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3fc0f995-3fb0-4a27-ba21-fb89edc4f6bc",
                            Email = "pascoaljose79@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Pascoal",
                            LastName = "José",
                            LockoutEnabled = false,
                            NormalizedEmail = "PASCOALJOSE79@GMAIL.COM",
                            NormalizedUserName = "PASCOALJOSE79@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH/0LH3ITM3mXmEKc/I0DlSoRzqe4a0G+4M6K1PkkCg+ys7diDwxyvR50YN1NCAxqQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "782d1aef-c496-444e-805c-613580edf3c2",
                            TwoFactorEnabled = false,
                            UserName = "pascoaljose79@gmail.com"
                        },
                        new
                        {
                            Id = "4a2b3c4d-0004-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d249ecec-fcbd-4b81-aa03-384b67001066",
                            Email = "manuellima171@hotmail.com",
                            EmailConfirmed = true,
                            FirstName = "Manuel",
                            LastName = "Lima",
                            LockoutEnabled = false,
                            NormalizedEmail = "MANUELLIMA171@HOTMAIL.COM",
                            NormalizedUserName = "MANUELLIMA171@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJW3oajGiXbcvRve8nsctEK22wes8PFQQgzJqh3fBna0YJFCr6pi51uxyLYeONKxUQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "160063ba-a479-4789-a488-b29e573b82ff",
                            TwoFactorEnabled = false,
                            UserName = "manuellima171@hotmail.com"
                        },
                        new
                        {
                            Id = "5a2b3c4d-0005-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2fb82a07-c129-490d-a6ce-4e701d894896",
                            Email = "GANT@equinor.com",
                            EmailConfirmed = true,
                            FirstName = "Gabriel",
                            LastName = "Antonio",
                            LockoutEnabled = false,
                            NormalizedEmail = "GANT@EQUINOR.COM",
                            NormalizedUserName = "GANT@EQUINOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELxpfTPfj+FZ95p/BIHLaQTLLJMENdglGnRVDVdtUWW4DhJ+U64X2wZxlbEStscTYg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2050c622-dfcd-4a40-aa16-345a2d31d739",
                            TwoFactorEnabled = false,
                            UserName = "GANT@equinor.com"
                        },
                        new
                        {
                            Id = "6a2b3c4d-0006-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3629bf3e-2923-4d9d-beda-a47ae0ae1d73",
                            Email = "Trindadeluis60@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Trindade",
                            LastName = "Luis",
                            LockoutEnabled = false,
                            NormalizedEmail = "TRINDADELUIS60@GMAIL.COM",
                            NormalizedUserName = "TRINDADELUIS60@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMa2zm8SI6EcXaDgKIwEICtBoyfdnXFUBWxHh75YNkumpkHp/qdRXUIw+jBJBmLn3Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dd1716e1-b16f-4e8f-b478-07a17fe81fb1",
                            TwoFactorEnabled = false,
                            UserName = "Trindadeluis60@gmail.com"
                        },
                        new
                        {
                            Id = "7a2b3c4d-0007-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8a411a15-3405-4352-9ecf-e096df36bbb1",
                            Email = "fleetbp.one@equador.co.ao",
                            EmailConfirmed = true,
                            FirstName = "Almeida",
                            LastName = "Inorio",
                            LockoutEnabled = false,
                            NormalizedEmail = "FLEETBP.ONE@EQUADOR.CO.AO",
                            NormalizedUserName = "FLEETBP.ONE@EQUADOR.CO.AO",
                            PasswordHash = "AQAAAAIAAYagAAAAELxMKHFLxa00r9vLWp8lmZ2aTdhypzEdT3eZqTADUVhVNZxEMs92ax4j/OH0tUfrog==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3853ab5b-e7d3-4e65-8e13-b01c8bab5c25",
                            TwoFactorEnabled = false,
                            UserName = "fleetbp.one@equador.co.ao"
                        },
                        new
                        {
                            Id = "8a2b3c4d-0008-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7aa70c46-b747-498e-8fdc-bd927bb4fcc7",
                            Email = "fleetbp.two@equador.co.ao",
                            EmailConfirmed = true,
                            FirstName = "Alfredo",
                            LastName = "Matos",
                            LockoutEnabled = false,
                            NormalizedEmail = "FLEETBP.TWO@EQUADOR.CO.AO",
                            NormalizedUserName = "FLEETBP.TWO@EQUADOR.CO.AO",
                            PasswordHash = "AQAAAAIAAYagAAAAEL1U6k9tH92/Pp/S4hOz4QBf5FJzsU+zqe0M5mOdBrj053IFT50NKjXralKH32eMPg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "582596ec-c4ce-4a49-9eaf-933e659d05a7",
                            TwoFactorEnabled = false,
                            UserName = "fleetbp.two@equador.co.ao"
                        },
                        new
                        {
                            Id = "9a2b3c4d-0009-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "95cf2500-074e-46db-af22-215fac7a8772",
                            Email = "fleetbp.three@equador.co.ao",
                            EmailConfirmed = true,
                            FirstName = "Ilisio",
                            LastName = "dos Santos",
                            LockoutEnabled = false,
                            NormalizedEmail = "FLEETBP.THREE@EQUADOR.CO.AO",
                            NormalizedUserName = "FLEETBP.THREE@EQUADOR.CO.AO",
                            PasswordHash = "AQAAAAIAAYagAAAAEOIkX2QOWl4q2fk2OFyOZ4TsyVxMF6T0Xhn1k4yR1+XW23ligRF/2NDatt7JF9hIMw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cf69a2d3-92ec-4908-bab7-95eafb5a65dd",
                            TwoFactorEnabled = false,
                            UserName = "fleetbp.three@equador.co.ao"
                        },
                        new
                        {
                            Id = "1b2b3c4d-0010-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f6a1ab17-6256-4d1a-adaf-a69e64d0bc10",
                            Email = "armandosuca@etuenergias.co.ao",
                            EmailConfirmed = true,
                            FirstName = "Armando",
                            LastName = "Suca",
                            LockoutEnabled = false,
                            NormalizedEmail = "ARMANDOSUCA@ETUENERGIAS.CO.AO",
                            NormalizedUserName = "ARMANDOSUCA@ETUENERGIAS.CO.AO",
                            PasswordHash = "AQAAAAIAAYagAAAAENwrJJdn3crrvhwv0qda6PwlYrS4khfTdOJxc1YACz9Pclns1YlB7zOzd32N+aumNw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e9d0b1eb-cb73-40e1-80f1-e0f1864997a3",
                            TwoFactorEnabled = false,
                            UserName = "armandosuca@etuenergias.co.ao"
                        },
                        new
                        {
                            Id = "2b2b3c4d-0011-4421-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57d88fb5-2ebe-48f7-a1b0-bf0139fff237",
                            Email = "magalhaes.equador@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "João",
                            LastName = "Magalhães",
                            LockoutEnabled = false,
                            NormalizedEmail = "MAGALHAES.EQUADOR@GMAIL.COM",
                            NormalizedUserName = "MAGALHAES.EQUADOR@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEP/WjrOQ0r0znmhXExsLa9NueMwwEHIjUO5YQT5o5QWPfLXt9oSNTyIyz2UIK87xhQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0ac55b76-c7d3-41c5-95fd-af74b084da17",
                            TwoFactorEnabled = false,
                            UserName = "magalhaes.equador@gmail.com"
                        },
                        new
                        {
                            Id = "1a2b3c4d-0002-4821-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f500a981-5b63-454b-b897-9578e79bfdc4",
                            Email = "bmml@alngopco.com",
                            EmailConfirmed = true,
                            FirstName = "Manuel",
                            LastName = "de Brito",
                            LockoutEnabled = false,
                            NormalizedEmail = "BMML@ALNGOPCO.COM",
                            NormalizedUserName = "BMML@ALNGOPCO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA3EuoAhMzZ3f/I9nmCS4gsju3L78VlH7CGDDBkiIzQQyoYSGMg4iAVuG0bZzkgrbg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c0ebacba-a262-4d4d-b90b-66d450d29fc1",
                            TwoFactorEnabled = false,
                            UserName = "bmml@alngopco.com"
                        },
                        new
                        {
                            Id = "1a2b3c4d-0003-4821-8342-7269ec64d949",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "56c45b23-0a46-4571-84f4-33e9b64774ab",
                            Email = "orlando.equador@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Orlando",
                            LastName = "Chico",
                            LockoutEnabled = false,
                            NormalizedEmail = "ORLANDO.EQUADOR@GMAIL.COM",
                            NormalizedUserName = "ORLANDO.EQUADOR@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG5TrXmt+MylTIy2aqh1/rA35Ie4lqCWPuNKNrKpOObuL8xiyLel+uqgx5RLx/dt+Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d0718ad4-8c76-4d50-8b38-eac5998516ec",
                            TwoFactorEnabled = false,
                            UserName = "orlando.equador@gmail.com"
                        });
                });

            modelBuilder.Entity("PortalEquador.Data.GroupTypes.entities.GroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("EditorId");

                    b.ToTable("GroupEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GroupEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EditorId");

                    b.HasIndex("GroupEntityId");

                    b.ToTable("GroupItemEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Languages.entity.LanguageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsMaternalLanguage")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("OralLevelId")
                        .HasColumnType("int");

                    b.Property<int>("PersonalInformationId")
                        .HasColumnType("int");

                    b.Property<int>("WrittenLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditorId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("OralLevelId");

                    b.HasIndex("PersonalInformationId");

                    b.HasIndex("WrittenLevelId");

                    b.ToTable("LanguageEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.MechanicalWorkshop.Admin.Entity.AdminMechanicalWorkShopContractEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("EditorId");

                    b.ToTable("AdminMechanicalWorkShopContractEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.MechanicalWorkshop.CarWash.Entity.CarWashSchedulerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InterventionTimeId")
                        .HasColumnType("int");

                    b.Property<int>("LaneId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("EditorId");

                    b.HasIndex("InterventionTimeId");

                    b.HasIndex("LaneId");

                    b.HasIndex("VehicleId");

                    b.ToTable("CarWashSchedulerEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.MechanicalWorkshop.Scheduler.Entity.MechanicalWorkshopSchedulerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InterventionTimeId")
                        .HasColumnType("int");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("EditorId");

                    b.HasIndex("InterventionTimeId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("VehicleId");

                    b.ToTable("MechanicalWorkshopSchedulerEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.MechanicalWorkshop.Vehicle.Entity.MechanicalWorkshopVehicleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LicencePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("EditorId");

                    b.ToTable("MechanicalWorkshopVehicleEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.MedicalExam.Entity.MedicalExamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonalInformationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditorId");

                    b.HasIndex("ExamId");

                    b.HasIndex("PersonalInformationId");

                    b.ToTable("MedicalExamEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.PersonalInformation.Entity.PersonalInformationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeneficiaryNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IdentityCardExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaritalStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("MotherTongueId")
                        .HasColumnType("int");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.Property<int>("NeighbourhoodId")
                        .HasColumnType("int");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditorId");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("MotherTongueId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("NeighbourhoodId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("PersonalInformationEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Profession.Competence.Entity.ProfessionalCompetenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PersonalInformationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceId");

                    b.HasIndex("EditorId");

                    b.HasIndex("PersonalInformationId");

                    b.ToTable("ProfessionalCompetenceEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Profession.Experience.Entity.ProfessionalExperienceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Months")
                        .HasColumnType("int");

                    b.Property<int>("PersonalInformationId")
                        .HasColumnType("int");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EditorId");

                    b.HasIndex("PersonalInformationId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("ProfessionalExperienceEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Trainning.Entity.TrainningEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonalInformationId")
                        .HasColumnType("int");

                    b.Property<int>("TrainningId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditorId");

                    b.HasIndex("PersonalInformationId");

                    b.HasIndex("TrainningId");

                    b.ToTable("TrainningEntity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalEquador.Data.Curriculum.Entities.CurriculumEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.DisciplinaryNotification.Entity.DisciplinaryNotificationEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "AccidentLevelGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("AccidentLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "NotificationGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.PersonalInformation.Entity.PersonalInformationEntity", "PersonalInformationEntity")
                        .WithMany()
                        .HasForeignKey("PersonalInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccidentLevelGroupItemEntity");

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("NotificationGroupItemEntity");

                    b.Navigation("PersonalInformationEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Document.Entity.DocumentEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "DocumentTypeGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.PersonalInformation.Entity.PersonalInformationEntity", "PersonalInformationEntity")
                        .WithMany()
                        .HasForeignKey("PersonalInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "SubTypeGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("SubTypeId");

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("DocumentTypeGroupItemEntity");

                    b.Navigation("PersonalInformationEntity");

                    b.Navigation("SubTypeGroupItemEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.DriversLicence.Entity.DriversLicenceEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "LicenceTypeGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("LicenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.PersonalInformation.Entity.PersonalInformationEntity", "PersonalInformationEntity")
                        .WithMany()
                        .HasForeignKey("PersonalInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("LicenceTypeGroupItemEntity");

                    b.Navigation("PersonalInformationEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Education.School.Entity.SchoolEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "DegreeGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "InstitutionGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "MajorGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("MajorId");

                    b.HasOne("PortalEquador.Data.PersonalInformation.Entity.PersonalInformationEntity", "PersonalInformationEntity")
                        .WithMany()
                        .HasForeignKey("PersonalInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("DegreeGroupItemEntity");

                    b.Navigation("InstitutionGroupItemEntity");

                    b.Navigation("MajorGroupItemEntity");

                    b.Navigation("PersonalInformationEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Education.University.Entity.UniversityEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "DegreeGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "InstitutionGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "MajorGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.PersonalInformation.Entity.PersonalInformationEntity", "PersonalInformationEntity")
                        .WithMany()
                        .HasForeignKey("PersonalInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("DegreeGroupItemEntity");

                    b.Navigation("InstitutionGroupItemEntity");

                    b.Navigation("MajorGroupItemEntity");

                    b.Navigation("PersonalInformationEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.GroupTypes.entities.GroupEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupEntity", "GroupEntity")
                        .WithMany()
                        .HasForeignKey("GroupEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("GroupEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Languages.entity.LanguageEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "LanguageGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "OralLevelGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("OralLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.PersonalInformation.Entity.PersonalInformationEntity", "PersonalInformationEntity")
                        .WithMany()
                        .HasForeignKey("PersonalInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "WrittenLevelGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("WrittenLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("LanguageGroupItemEntity");

                    b.Navigation("OralLevelGroupItemEntity");

                    b.Navigation("PersonalInformationEntity");

                    b.Navigation("WrittenLevelGroupItemEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.MechanicalWorkshop.Admin.Entity.AdminMechanicalWorkShopContractEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "ContractGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("ContractGroupItemEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.MechanicalWorkshop.CarWash.Entity.CarWashSchedulerEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "ContractGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "InterventionTimeGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("InterventionTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "LaneGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("LaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.MechanicalWorkshop.Vehicle.Entity.MechanicalWorkshopVehicleEntity", "VehicleEntity")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("ContractGroupItemEntity");

                    b.Navigation("InterventionTimeGroupItemEntity");

                    b.Navigation("LaneGroupItemEntity");

                    b.Navigation("VehicleEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.MechanicalWorkshop.Scheduler.Entity.MechanicalWorkshopSchedulerEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "ContractGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "InterventionTimeGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("InterventionTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "MechanicGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.MechanicalWorkshop.Vehicle.Entity.MechanicalWorkshopVehicleEntity", "VehicleEntity")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("ContractGroupItemEntity");

                    b.Navigation("InterventionTimeGroupItemEntity");

                    b.Navigation("MechanicGroupItemEntity");

                    b.Navigation("VehicleEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.MechanicalWorkshop.Vehicle.Entity.MechanicalWorkshopVehicleEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "ContractGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("ContractGroupItemEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.MedicalExam.Entity.MedicalExamEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "ExamGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.PersonalInformation.Entity.PersonalInformationEntity", "PersonalInformationEntity")
                        .WithMany()
                        .HasForeignKey("PersonalInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("ExamGroupItemEntity");

                    b.Navigation("PersonalInformationEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.PersonalInformation.Entity.PersonalInformationEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "MaritalStatusIdGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("MaritalStatusId");

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "MotherTongueGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("MotherTongueId");

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "NationalityGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "NeighbourhoodGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("NeighbourhoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "ProvinceGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("ProvinceId");

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("MaritalStatusIdGroupItemEntity");

                    b.Navigation("MotherTongueGroupItemEntity");

                    b.Navigation("NationalityGroupItemEntity");

                    b.Navigation("NeighbourhoodGroupItemEntity");

                    b.Navigation("ProvinceGroupItemEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Profession.Competence.Entity.ProfessionalCompetenceEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "CompetenceGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.PersonalInformation.Entity.PersonalInformationEntity", "PersonalInformationEntity")
                        .WithMany()
                        .HasForeignKey("PersonalInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("CompetenceGroupItemEntity");

                    b.Navigation("PersonalInformationEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Profession.Experience.Entity.ProfessionalExperienceEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "CompanyGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.PersonalInformation.Entity.PersonalInformationEntity", "PersonalInformationEntity")
                        .WithMany()
                        .HasForeignKey("PersonalInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "WorkstationGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("CompanyGroupItemEntity");

                    b.Navigation("PersonalInformationEntity");

                    b.Navigation("WorkstationGroupItemEntity");
                });

            modelBuilder.Entity("PortalEquador.Data.Trainning.Entity.TrainningEntity", b =>
                {
                    b.HasOne("PortalEquador.Data.Generic.ApplicationUser", "ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.PersonalInformation.Entity.PersonalInformationEntity", "PersonalInformationEntity")
                        .WithMany()
                        .HasForeignKey("PersonalInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalEquador.Data.GroupTypes.entities.GroupItemEntity", "TrainningGroupItemEntity")
                        .WithMany()
                        .HasForeignKey("TrainningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUserEntity");

                    b.Navigation("PersonalInformationEntity");

                    b.Navigation("TrainningGroupItemEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
